boolean muteControl;

void audio(){
  if(start){
  bass1.mute();
  bass2.unmute();
  backing.unmute();
  perc.mute();
  melody.mute();
  winMelody.mute();
  }
  if(game){
  bass1.mute();
  bass2.unmute();
  backing.unmute();
  perc.unmute();
  melody.mute();
  winMelody.mute();
    if(stage[1]){
    bass1.mute();
    bass2.unmute();
    backing.unmute();
    perc.unmute();
    melody.unmute();
    winMelody.mute();
    }
    if(stage[4]){
    bass1.unmute();
    bass2.unmute();
    backing.unmute();
    perc.unmute();
    melody.unmute();
    winMelody.mute();
    }
  }
  if(gameover){
  bass1.unmute();
  bass2.mute();
  backing.mute();
  perc.mute();
  melody.mute();
  winMelody.mute();
  }
  if(win){
  bass1.unmute();
  bass2.unmute();
  backing.unmute();
  perc.unmute();
  melody.unmute();
  winMelody.unmute();
  }
  
  //if(muteControl){
  //  bass1.pause();
  //bass2.pause();
  //backing.pause();
  //perc.pause();
  //melody.pause();
  //winMelody.pause();
  //}
  //else if(!muteControl){
  //bass1.loop();
  //bass2.loop();
  //backing.loop();
  //perc.loop();
  //melody.loop();
  //winMelody.loop();
  //}
}
